package configuration

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestLoadFull(t *testing.T) {
	cfg, err := GetStorageConfiguration("testdata/fullconfig.json")
	require.Nil(t, err)
	require.Equal(t, "cert.pem", cfg.Tls.CertFile)
	require.Equal(t, ":4251", cfg.GrpcListenAddress)
}

func TestLoadFull_TLSInline(t *testing.T) {
	cfg, err := GetStorageConfiguration("testdata/fullconfig-tlsinline.json")
	require.Nil(t, err)
	require.Equal(t, `-----BEGIN CERTIFICATE-----
MIIF5jCCA86gAwIBAgIJAO2nShtreN/TMA0GCSqGSIb3DQEBCwUAMIGHMQswCQYD
VQQGEwJHQjEWMBQGA1UECAwNSGVydGZvcmRzaGlyZTESMBAGA1UEBwwJQ2FtYnJp
ZGdlMR4wHAYDVQQKDBVCYXJuIEJ1aWxkZXJzIFB0eSBMdGQxFjAUBgNVBAsMDUhh
eSBSZXNvdXJjZXMxFDASBgNVBAMMC2hheS5iYi5mYXJtMB4XDTE5MDUxMDIyMjIz
NloXDTIwMDUwOTIyMjIzNlowgYcxCzAJBgNVBAYTAkdCMRYwFAYDVQQIDA1IZXJ0
Zm9yZHNoaXJlMRIwEAYDVQQHDAlDYW1icmlkZ2UxHjAcBgNVBAoMFUJhcm4gQnVp
bGRlcnMgUHR5IEx0ZDEWMBQGA1UECwwNSGF5IFJlc291cmNlczEUMBIGA1UEAwwL
aGF5LmJiLmZhcm0wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQChpZK0
HY1skOVEcXb2gYEo9T3hiKazPSwCp2qNOssIB7oAfxSf70VuPwibY4gjQchODIWP
45Ui3Jaj9BuOS7qlIvYUyqpz5wEtLbI9s3CtKDZm6jaSUaBlWVJ2BPUTyOHxLkiy
lV9lH+2N8ojlpN1rx+xDRd/iLSu1eD/tEZfFSF0EJZgBiAGHAofOAKafHKn/Upxq
vHaGHdMYxJttV6s/VyTk76U5yg4guzYHhDPLHJkBMdU2ExSs7j3nMMvtFTq03DYY
E4p/YVTuu4vBjWbQZ8sQe7NdoRlvWzATh8uysBn3ym6U0T+1rQPmc5HJsgN6yOsu
EJvNjQaHVNBEyggHcSVGrnQfVhmSzp4LyO168ZcYTjivRQi33WEuH8vNhRaPneiG
Ng3N3P/DPMRv5JIjN15nb5ok8C1kKB15PznjgM8RIBd0XpkulEwvjAG7vVAEVLec
+pbQpaYvZi+RtXoH/eNaGDZLPR5AvSaNtPcgCubxuedIwbOj/f8pr1I3YDGKIStI
9x4L7U6lZfG/nikP+N0KLt0SxdCsHH55DBe1JAfniWaUcJASOADjkMz/GJKU7TjO
0FTLYgzOXlNjyZ/o8yM6tOrsOWd+pVXGm7vSG5NuObb89mghcLvMkuumKqLBnVuD
SrSZ4EQgL9hSfHp+t/k/rygkItAKIdbyZ0s5gwIDAQABo1MwUTAdBgNVHQ4EFgQU
3UF21ksLeZFspA7tuFQQ5NPD8GAwHwYDVR0jBBgwFoAU3UF21ksLeZFspA7tuFQQ
5NPD8GAwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAEdG4Zmli
r5gFk+bJlS7wNJj/voEQcL/bdrmPm+H0VnoWxDVjjYBtn6kUfyXxpfpi/0/fYfrP
gX9XuxjKigblyTwbRjStfvvvIgb74QYecgpCAtcv5swNIAVpcgag0JobSQlw85JI
ObnVhTw9yGIuzl19FXyJ8l2n/B13BQ7MVx/A8M3aZPg1f5Mtl/x1TQo2wwAnJpUG
ZOS91ccwtTS8uo9X8dzjCItkQg7VK14n60pXFEUi3w4CrDmq5rY/8kU7BA8aPjZQ
qt3vJYL9HmSk5J7f/5/7gNzdqf1xC+zqgyyTIHncMpLwLVNzaanTRYKdoHu0XL27
ASmJ+qO4NsjOJED5O1kdrn7ApJ2NLT32aXzqWsuuctzZ5kLQlREbfEdXiPbRDBlT
0hZTtLMakxfjjvUg5uw/302TRdt0UqHyslbXlZekkXZtzQmU6HK5nes55TA9kDwz
op6//TQL/vfpAqnLEWxSknv8q4n9635MfmbyTIVHFmiGw3w/leKYl83RI/0CnPRk
q81zXtUQsLkpm1ZhI8JZbfSiTcmT/RH1nIljZOtqjf3p6Fmm2vYMLWVuuAmxNmmm
iSWn9ivT3tFL9AjuEHOBjqkVwRB1HzUeyejDmBg968ldPV/9Sh2dWvTVEfvQ7Sic
Qyelh/2wseRhE4iuh5cb03zBli0uwxIXbIE=
-----END CERTIFICATE-----`, cfg.Tls.Cert)
	require.Equal(t, ":4251", cfg.GrpcListenAddress)
}
