load("@rules_go//go:def.bzl", "go_library", "go_test")

exports_files(["coder.go"])

go_library(
    name = "coder",
    srcs = [
        "chunk_coder.go",
        "chunk_list_coder.go",
        "coder.go",
        "proto_coder.go",
        "xxh64_suffix_coder.go",
        "zstd_coder.go",
    ],
    importpath = "github.com/buildbarn/bb-storage/pkg/blobstore/coder",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/blobstore/chunk",
        "//pkg/digest",
        "//pkg/util",
        "//pkg/zstd",
        "@bazel_remote_apis//build/bazel/remote/execution/v2:remote_execution_go_proto",
        "@com_github_cespare_xxhash_v2//:xxhash",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//proto",
    ],
)

go_test(
    name = "coder_test",
    srcs = ["chunk_coder_test.go"],
    deps = [
        ":coder",
        "//pkg/blobstore/chunk",
        "//pkg/digest",
        "//pkg/testutil",
        "//pkg/zstd",
        "@bazel_remote_apis//build/bazel/remote/execution/v2:remote_execution_go_proto",
        "@com_github_stretchr_testify//require",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)
