// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: github.com/buildbarn/bb-storage/pkg/proto/auth/auth.proto

package auth

import (
	v1 "go.opentelemetry.io/proto/otlp/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticationMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Public            *structpb.Value        `protobuf:"bytes,1,opt,name=public,proto3" json:"public,omitempty"`
	TracingAttributes []*v1.KeyValue         `protobuf:"bytes,2,rep,name=tracing_attributes,json=tracingAttributes,proto3" json:"tracing_attributes,omitempty"`
	Private           *structpb.Value        `protobuf:"bytes,3,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthenticationMetadata) Reset() {
	*x = AuthenticationMetadata{}
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationMetadata) ProtoMessage() {}

func (x *AuthenticationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationMetadata.ProtoReflect.Descriptor instead.
func (*AuthenticationMetadata) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticationMetadata) GetPublic() *structpb.Value {
	if x != nil {
		return x.Public
	}
	return nil
}

func (x *AuthenticationMetadata) GetTracingAttributes() []*v1.KeyValue {
	if x != nil {
		return x.TracingAttributes
	}
	return nil
}

func (x *AuthenticationMetadata) GetPrivate() *structpb.Value {
	if x != nil {
		return x.Private
	}
	return nil
}

type AuthenticateRequest struct {
	state           protoimpl.MessageState                    `protogen:"open.v1"`
	RequestMetadata map[string]*AuthenticateRequest_ValueList `protobuf:"bytes,1,rep,name=request_metadata,json=requestMetadata,proto3" json:"request_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Scope           *structpb.Value                           `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateRequest) GetRequestMetadata() map[string]*AuthenticateRequest_ValueList {
	if x != nil {
		return x.RequestMetadata
	}
	return nil
}

func (x *AuthenticateRequest) GetScope() *structpb.Value {
	if x != nil {
		return x.Scope
	}
	return nil
}

type AuthenticateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Verdict:
	//
	//	*AuthenticateResponse_Allow
	//	*AuthenticateResponse_Deny
	Verdict             isAuthenticateResponse_Verdict `protobuf_oneof:"verdict"`
	CacheExpirationTime *timestamppb.Timestamp         `protobuf:"bytes,3,opt,name=cache_expiration_time,json=cacheExpirationTime,proto3" json:"cache_expiration_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticateResponse) GetVerdict() isAuthenticateResponse_Verdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

func (x *AuthenticateResponse) GetAllow() *AuthenticationMetadata {
	if x != nil {
		if x, ok := x.Verdict.(*AuthenticateResponse_Allow); ok {
			return x.Allow
		}
	}
	return nil
}

func (x *AuthenticateResponse) GetDeny() string {
	if x != nil {
		if x, ok := x.Verdict.(*AuthenticateResponse_Deny); ok {
			return x.Deny
		}
	}
	return ""
}

func (x *AuthenticateResponse) GetCacheExpirationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CacheExpirationTime
	}
	return nil
}

type isAuthenticateResponse_Verdict interface {
	isAuthenticateResponse_Verdict()
}

type AuthenticateResponse_Allow struct {
	Allow *AuthenticationMetadata `protobuf:"bytes,1,opt,name=allow,proto3,oneof"`
}

type AuthenticateResponse_Deny struct {
	Deny string `protobuf:"bytes,2,opt,name=deny,proto3,oneof"`
}

func (*AuthenticateResponse_Allow) isAuthenticateResponse_Verdict() {}

func (*AuthenticateResponse_Deny) isAuthenticateResponse_Verdict() {}

type AuthorizeRequest struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	AuthenticationMetadata *AuthenticationMetadata `protobuf:"bytes,1,opt,name=authentication_metadata,json=authenticationMetadata,proto3" json:"authentication_metadata,omitempty"`
	Scope                  *structpb.Value         `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	InstanceName           string                  `protobuf:"bytes,3,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizeRequest) GetAuthenticationMetadata() *AuthenticationMetadata {
	if x != nil {
		return x.AuthenticationMetadata
	}
	return nil
}

func (x *AuthorizeRequest) GetScope() *structpb.Value {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *AuthorizeRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

type AuthorizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Verdict:
	//
	//	*AuthorizeResponse_Allow
	//	*AuthorizeResponse_Deny
	Verdict             isAuthorizeResponse_Verdict `protobuf_oneof:"verdict"`
	CacheExpirationTime *timestamppb.Timestamp      `protobuf:"bytes,3,opt,name=cache_expiration_time,json=cacheExpirationTime,proto3" json:"cache_expiration_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizeResponse) GetVerdict() isAuthorizeResponse_Verdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

func (x *AuthorizeResponse) GetAllow() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Verdict.(*AuthorizeResponse_Allow); ok {
			return x.Allow
		}
	}
	return nil
}

func (x *AuthorizeResponse) GetDeny() string {
	if x != nil {
		if x, ok := x.Verdict.(*AuthorizeResponse_Deny); ok {
			return x.Deny
		}
	}
	return ""
}

func (x *AuthorizeResponse) GetCacheExpirationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CacheExpirationTime
	}
	return nil
}

type isAuthorizeResponse_Verdict interface {
	isAuthorizeResponse_Verdict()
}

type AuthorizeResponse_Allow struct {
	Allow *emptypb.Empty `protobuf:"bytes,1,opt,name=allow,proto3,oneof"`
}

type AuthorizeResponse_Deny struct {
	Deny string `protobuf:"bytes,2,opt,name=deny,proto3,oneof"`
}

func (*AuthorizeResponse_Allow) isAuthorizeResponse_Verdict() {}

func (*AuthorizeResponse_Deny) isAuthorizeResponse_Verdict() {}

type AuthenticateRequest_ValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []string               `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest_ValueList) Reset() {
	*x = AuthenticateRequest_ValueList{}
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest_ValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest_ValueList) ProtoMessage() {}

func (x *AuthenticateRequest_ValueList) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest_ValueList.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest_ValueList) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AuthenticateRequest_ValueList) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDesc = "" +
	"\n" +
	"9github.com/buildbarn/bb-storage/pkg/proto/auth/auth.proto\x12\x0ebuildbarn.auth\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a*opentelemetry/proto/common/v1/common.proto\"\xd2\x01\n" +
	"\x16AuthenticationMetadata\x12.\n" +
	"\x06public\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x06public\x12V\n" +
	"\x12tracing_attributes\x18\x02 \x03(\v2'.opentelemetry.proto.common.v1.KeyValueR\x11tracingAttributes\x120\n" +
	"\aprivate\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\aprivate\"\xbe\x02\n" +
	"\x13AuthenticateRequest\x12c\n" +
	"\x10request_metadata\x18\x01 \x03(\v28.buildbarn.auth.AuthenticateRequest.RequestMetadataEntryR\x0frequestMetadata\x12,\n" +
	"\x05scope\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05scope\x1a!\n" +
	"\tValueList\x12\x14\n" +
	"\x05value\x18\x01 \x03(\tR\x05value\x1aq\n" +
	"\x14RequestMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12C\n" +
	"\x05value\x18\x02 \x01(\v2-.buildbarn.auth.AuthenticateRequest.ValueListR\x05value:\x028\x01\"\xc7\x01\n" +
	"\x14AuthenticateResponse\x12>\n" +
	"\x05allow\x18\x01 \x01(\v2&.buildbarn.auth.AuthenticationMetadataH\x00R\x05allow\x12\x14\n" +
	"\x04deny\x18\x02 \x01(\tH\x00R\x04deny\x12N\n" +
	"\x15cache_expiration_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x13cacheExpirationTimeB\t\n" +
	"\averdict\"\xc6\x01\n" +
	"\x10AuthorizeRequest\x12_\n" +
	"\x17authentication_metadata\x18\x01 \x01(\v2&.buildbarn.auth.AuthenticationMetadataR\x16authenticationMetadata\x12,\n" +
	"\x05scope\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05scope\x12#\n" +
	"\rinstance_name\x18\x03 \x01(\tR\finstanceName\"\xb4\x01\n" +
	"\x11AuthorizeResponse\x12.\n" +
	"\x05allow\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x05allow\x12\x14\n" +
	"\x04deny\x18\x02 \x01(\tH\x00R\x04deny\x12N\n" +
	"\x15cache_expiration_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x13cacheExpirationTimeB\t\n" +
	"\averdict2m\n" +
	"\x0eAuthentication\x12[\n" +
	"\fAuthenticate\x12#.buildbarn.auth.AuthenticateRequest\x1a$.buildbarn.auth.AuthenticateResponse\"\x002`\n" +
	"\n" +
	"Authorizer\x12R\n" +
	"\tAuthorize\x12 .buildbarn.auth.AuthorizeRequest\x1a!.buildbarn.auth.AuthorizeResponse\"\x00B0Z.github.com/buildbarn/bb-storage/pkg/proto/authb\x06proto3"

var (
	file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDesc), len(file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDescData
}

var file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_goTypes = []any{
	(*AuthenticationMetadata)(nil),        // 0: buildbarn.auth.AuthenticationMetadata
	(*AuthenticateRequest)(nil),           // 1: buildbarn.auth.AuthenticateRequest
	(*AuthenticateResponse)(nil),          // 2: buildbarn.auth.AuthenticateResponse
	(*AuthorizeRequest)(nil),              // 3: buildbarn.auth.AuthorizeRequest
	(*AuthorizeResponse)(nil),             // 4: buildbarn.auth.AuthorizeResponse
	(*AuthenticateRequest_ValueList)(nil), // 5: buildbarn.auth.AuthenticateRequest.ValueList
	nil,                                   // 6: buildbarn.auth.AuthenticateRequest.RequestMetadataEntry
	(*structpb.Value)(nil),                // 7: google.protobuf.Value
	(*v1.KeyValue)(nil),                   // 8: opentelemetry.proto.common.v1.KeyValue
	(*timestamppb.Timestamp)(nil),         // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 10: google.protobuf.Empty
}
var file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_depIdxs = []int32{
	7,  // 0: buildbarn.auth.AuthenticationMetadata.public:type_name -> google.protobuf.Value
	8,  // 1: buildbarn.auth.AuthenticationMetadata.tracing_attributes:type_name -> opentelemetry.proto.common.v1.KeyValue
	7,  // 2: buildbarn.auth.AuthenticationMetadata.private:type_name -> google.protobuf.Value
	6,  // 3: buildbarn.auth.AuthenticateRequest.request_metadata:type_name -> buildbarn.auth.AuthenticateRequest.RequestMetadataEntry
	7,  // 4: buildbarn.auth.AuthenticateRequest.scope:type_name -> google.protobuf.Value
	0,  // 5: buildbarn.auth.AuthenticateResponse.allow:type_name -> buildbarn.auth.AuthenticationMetadata
	9,  // 6: buildbarn.auth.AuthenticateResponse.cache_expiration_time:type_name -> google.protobuf.Timestamp
	0,  // 7: buildbarn.auth.AuthorizeRequest.authentication_metadata:type_name -> buildbarn.auth.AuthenticationMetadata
	7,  // 8: buildbarn.auth.AuthorizeRequest.scope:type_name -> google.protobuf.Value
	10, // 9: buildbarn.auth.AuthorizeResponse.allow:type_name -> google.protobuf.Empty
	9,  // 10: buildbarn.auth.AuthorizeResponse.cache_expiration_time:type_name -> google.protobuf.Timestamp
	5,  // 11: buildbarn.auth.AuthenticateRequest.RequestMetadataEntry.value:type_name -> buildbarn.auth.AuthenticateRequest.ValueList
	1,  // 12: buildbarn.auth.Authentication.Authenticate:input_type -> buildbarn.auth.AuthenticateRequest
	3,  // 13: buildbarn.auth.Authorizer.Authorize:input_type -> buildbarn.auth.AuthorizeRequest
	2,  // 14: buildbarn.auth.Authentication.Authenticate:output_type -> buildbarn.auth.AuthenticateResponse
	4,  // 15: buildbarn.auth.Authorizer.Authorize:output_type -> buildbarn.auth.AuthorizeResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_init() }
func file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_init() {
	if File_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto != nil {
		return
	}
	file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_msgTypes[2].OneofWrappers = []any{
		(*AuthenticateResponse_Allow)(nil),
		(*AuthenticateResponse_Deny)(nil),
	}
	file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_msgTypes[4].OneofWrappers = []any{
		(*AuthorizeResponse_Allow)(nil),
		(*AuthorizeResponse_Deny)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDesc), len(file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto = out.File
	file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_goTypes = nil
	file_github_com_buildbarn_bb_storage_pkg_proto_auth_auth_proto_depIdxs = nil
}
