load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cdc",
    srcs = [
        "bypass.go",
        "caching_parameters_fetcher.go",
        "chunker.go",
        "parameters.go",
        "reader_chunker.go",
    ],
    importpath = "github.com/buildbarn/bb-storage/pkg/blobstore/cdc",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/capabilities",
        "//pkg/digest",
        "//pkg/ttlcache",
        "//pkg/util",
        "@com_github_buildbarn_go_cdc//:go-cdc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)

go_test(
    name = "cdc_test",
    srcs = ["reader_chunker_test.go"],
    deps = [
        ":cdc",
        "//pkg/blobstore/buffer",
        "//pkg/digest",
        "@bazel_remote_apis//build/bazel/remote/execution/v2:remote_execution_go_proto",
        "@com_github_stretchr_testify//require",
    ],
)
