// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/configuration/jmespath/jmespath.proto

package jmespath

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Expression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	Files         []*File                `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	TestVectors   []*TestVector          `protobuf:"bytes,3,rep,name=test_vectors,json=testVectors,proto3" json:"test_vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expression) Reset() {
	*x = Expression{}
	mi := &file_pkg_proto_configuration_jmespath_jmespath_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_jmespath_jmespath_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_jmespath_jmespath_proto_rawDescGZIP(), []int{0}
}

func (x *Expression) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *Expression) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Expression) GetTestVectors() []*TestVector {
	if x != nil {
		return x.TestVectors
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_pkg_proto_configuration_jmespath_jmespath_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_jmespath_jmespath_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_jmespath_jmespath_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type TestVector struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Input          *structpb.Struct       `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	ExpectedOutput *structpb.Value        `protobuf:"bytes,2,opt,name=expected_output,json=expectedOutput,proto3" json:"expected_output,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestVector) Reset() {
	*x = TestVector{}
	mi := &file_pkg_proto_configuration_jmespath_jmespath_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestVector) ProtoMessage() {}

func (x *TestVector) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_jmespath_jmespath_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestVector.ProtoReflect.Descriptor instead.
func (*TestVector) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_jmespath_jmespath_proto_rawDescGZIP(), []int{2}
}

func (x *TestVector) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *TestVector) GetExpectedOutput() *structpb.Value {
	if x != nil {
		return x.ExpectedOutput
	}
	return nil
}

var File_pkg_proto_configuration_jmespath_jmespath_proto protoreflect.FileDescriptor

const file_pkg_proto_configuration_jmespath_jmespath_proto_rawDesc = "" +
	"\n" +
	"/pkg/proto/configuration/jmespath/jmespath.proto\x12 buildbarn.configuration.jmespath\x1a\x1cgoogle/protobuf/struct.proto\"\xbb\x01\n" +
	"\n" +
	"Expression\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12<\n" +
	"\x05files\x18\x02 \x03(\v2&.buildbarn.configuration.jmespath.FileR\x05files\x12O\n" +
	"\ftest_vectors\x18\x03 \x03(\v2,.buildbarn.configuration.jmespath.TestVectorR\vtestVectors\",\n" +
	"\x04File\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"|\n" +
	"\n" +
	"TestVector\x12-\n" +
	"\x05input\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05input\x12?\n" +
	"\x0fexpected_output\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x0eexpectedOutputBBZ@github.com/buildbarn/bb-storage/pkg/proto/configuration/jmespathb\x06proto3"

var (
	file_pkg_proto_configuration_jmespath_jmespath_proto_rawDescOnce sync.Once
	file_pkg_proto_configuration_jmespath_jmespath_proto_rawDescData []byte
)

func file_pkg_proto_configuration_jmespath_jmespath_proto_rawDescGZIP() []byte {
	file_pkg_proto_configuration_jmespath_jmespath_proto_rawDescOnce.Do(func() {
		file_pkg_proto_configuration_jmespath_jmespath_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_jmespath_jmespath_proto_rawDesc), len(file_pkg_proto_configuration_jmespath_jmespath_proto_rawDesc)))
	})
	return file_pkg_proto_configuration_jmespath_jmespath_proto_rawDescData
}

var file_pkg_proto_configuration_jmespath_jmespath_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_configuration_jmespath_jmespath_proto_goTypes = []any{
	(*Expression)(nil),      // 0: buildbarn.configuration.jmespath.Expression
	(*File)(nil),            // 1: buildbarn.configuration.jmespath.File
	(*TestVector)(nil),      // 2: buildbarn.configuration.jmespath.TestVector
	(*structpb.Struct)(nil), // 3: google.protobuf.Struct
	(*structpb.Value)(nil),  // 4: google.protobuf.Value
}
var file_pkg_proto_configuration_jmespath_jmespath_proto_depIdxs = []int32{
	1, // 0: buildbarn.configuration.jmespath.Expression.files:type_name -> buildbarn.configuration.jmespath.File
	2, // 1: buildbarn.configuration.jmespath.Expression.test_vectors:type_name -> buildbarn.configuration.jmespath.TestVector
	3, // 2: buildbarn.configuration.jmespath.TestVector.input:type_name -> google.protobuf.Struct
	4, // 3: buildbarn.configuration.jmespath.TestVector.expected_output:type_name -> google.protobuf.Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_configuration_jmespath_jmespath_proto_init() }
func file_pkg_proto_configuration_jmespath_jmespath_proto_init() {
	if File_pkg_proto_configuration_jmespath_jmespath_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_jmespath_jmespath_proto_rawDesc), len(file_pkg_proto_configuration_jmespath_jmespath_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_configuration_jmespath_jmespath_proto_goTypes,
		DependencyIndexes: file_pkg_proto_configuration_jmespath_jmespath_proto_depIdxs,
		MessageInfos:      file_pkg_proto_configuration_jmespath_jmespath_proto_msgTypes,
	}.Build()
	File_pkg_proto_configuration_jmespath_jmespath_proto = out.File
	file_pkg_proto_configuration_jmespath_jmespath_proto_goTypes = nil
	file_pkg_proto_configuration_jmespath_jmespath_proto_depIdxs = nil
}
