// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: github.com/buildbarn/bb-storage/pkg/proto/configuration/digest/digest.proto

package digest

import (
	eviction "github.com/buildbarn/bb-storage/pkg/proto/configuration/eviction"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExistenceCacheConfiguration struct {
	state                  protoimpl.MessageState          `protogen:"open.v1"`
	CacheSize              int64                           `protobuf:"varint,1,opt,name=cache_size,json=cacheSize,proto3" json:"cache_size,omitempty"`
	CacheDuration          *durationpb.Duration            `protobuf:"bytes,2,opt,name=cache_duration,json=cacheDuration,proto3" json:"cache_duration,omitempty"`
	CacheReplacementPolicy eviction.CacheReplacementPolicy `protobuf:"varint,3,opt,name=cache_replacement_policy,json=cacheReplacementPolicy,proto3,enum=buildbarn.configuration.eviction.CacheReplacementPolicy" json:"cache_replacement_policy,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExistenceCacheConfiguration) Reset() {
	*x = ExistenceCacheConfiguration{}
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistenceCacheConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistenceCacheConfiguration) ProtoMessage() {}

func (x *ExistenceCacheConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistenceCacheConfiguration.ProtoReflect.Descriptor instead.
func (*ExistenceCacheConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_rawDescGZIP(), []int{0}
}

func (x *ExistenceCacheConfiguration) GetCacheSize() int64 {
	if x != nil {
		return x.CacheSize
	}
	return 0
}

func (x *ExistenceCacheConfiguration) GetCacheDuration() *durationpb.Duration {
	if x != nil {
		return x.CacheDuration
	}
	return nil
}

func (x *ExistenceCacheConfiguration) GetCacheReplacementPolicy() eviction.CacheReplacementPolicy {
	if x != nil {
		return x.CacheReplacementPolicy
	}
	return eviction.CacheReplacementPolicy(0)
}

var File_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_rawDesc = "" +
	"\n" +
	"Kgithub.com/buildbarn/bb-storage/pkg/proto/configuration/digest/digest.proto\x12\x1ebuildbarn.configuration.digest\x1aOgithub.com/buildbarn/bb-storage/pkg/proto/configuration/eviction/eviction.proto\x1a\x1egoogle/protobuf/duration.proto\"\xf2\x01\n" +
	"\x1bExistenceCacheConfiguration\x12\x1d\n" +
	"\n" +
	"cache_size\x18\x01 \x01(\x03R\tcacheSize\x12@\n" +
	"\x0ecache_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\rcacheDuration\x12r\n" +
	"\x18cache_replacement_policy\x18\x03 \x01(\x0e28.buildbarn.configuration.eviction.CacheReplacementPolicyR\x16cacheReplacementPolicyB@Z>github.com/buildbarn/bb-storage/pkg/proto/configuration/digestb\x06proto3"

var (
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_rawDesc), len(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_rawDescData
}

var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_goTypes = []any{
	(*ExistenceCacheConfiguration)(nil),  // 0: buildbarn.configuration.digest.ExistenceCacheConfiguration
	(*durationpb.Duration)(nil),          // 1: google.protobuf.Duration
	(eviction.CacheReplacementPolicy)(0), // 2: buildbarn.configuration.eviction.CacheReplacementPolicy
}
var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_depIdxs = []int32{
	1, // 0: buildbarn.configuration.digest.ExistenceCacheConfiguration.cache_duration:type_name -> google.protobuf.Duration
	2, // 1: buildbarn.configuration.digest.ExistenceCacheConfiguration.cache_replacement_policy:type_name -> buildbarn.configuration.eviction.CacheReplacementPolicy
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_init() }
func file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_init() {
	if File_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_rawDesc), len(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto = out.File
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_goTypes = nil
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_digest_digest_proto_depIdxs = nil
}
