// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: github.com/buildbarn/bb-storage/pkg/proto/http/oidc/oidc.proto

package oidc

import (
	auth "github.com/buildbarn/bb-storage/pkg/proto/auth"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CookieValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to SessionState:
	//
	//	*CookieValue_Authenticating_
	//	*CookieValue_Authenticated_
	SessionState  isCookieValue_SessionState `protobuf_oneof:"session_state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CookieValue) Reset() {
	*x = CookieValue{}
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CookieValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookieValue) ProtoMessage() {}

func (x *CookieValue) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookieValue.ProtoReflect.Descriptor instead.
func (*CookieValue) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_rawDescGZIP(), []int{0}
}

func (x *CookieValue) GetSessionState() isCookieValue_SessionState {
	if x != nil {
		return x.SessionState
	}
	return nil
}

func (x *CookieValue) GetAuthenticating() *CookieValue_Authenticating {
	if x != nil {
		if x, ok := x.SessionState.(*CookieValue_Authenticating_); ok {
			return x.Authenticating
		}
	}
	return nil
}

func (x *CookieValue) GetAuthenticated() *CookieValue_Authenticated {
	if x != nil {
		if x, ok := x.SessionState.(*CookieValue_Authenticated_); ok {
			return x.Authenticated
		}
	}
	return nil
}

type isCookieValue_SessionState interface {
	isCookieValue_SessionState()
}

type CookieValue_Authenticating_ struct {
	Authenticating *CookieValue_Authenticating `protobuf:"bytes,1,opt,name=authenticating,proto3,oneof"`
}

type CookieValue_Authenticated_ struct {
	Authenticated *CookieValue_Authenticated `protobuf:"bytes,2,opt,name=authenticated,proto3,oneof"`
}

func (*CookieValue_Authenticating_) isCookieValue_SessionState() {}

func (*CookieValue_Authenticated_) isCookieValue_SessionState() {}

type CookieValue_Authenticating struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StateVerifier      []byte                 `protobuf:"bytes,1,opt,name=state_verifier,json=stateVerifier,proto3" json:"state_verifier,omitempty"`
	OriginalRequestUri string                 `protobuf:"bytes,2,opt,name=original_request_uri,json=originalRequestUri,proto3" json:"original_request_uri,omitempty"`
	CodeVerifier       []byte                 `protobuf:"bytes,3,opt,name=code_verifier,json=codeVerifier,proto3" json:"code_verifier,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CookieValue_Authenticating) Reset() {
	*x = CookieValue_Authenticating{}
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CookieValue_Authenticating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookieValue_Authenticating) ProtoMessage() {}

func (x *CookieValue_Authenticating) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookieValue_Authenticating.ProtoReflect.Descriptor instead.
func (*CookieValue_Authenticating) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CookieValue_Authenticating) GetStateVerifier() []byte {
	if x != nil {
		return x.StateVerifier
	}
	return nil
}

func (x *CookieValue_Authenticating) GetOriginalRequestUri() string {
	if x != nil {
		return x.OriginalRequestUri
	}
	return ""
}

func (x *CookieValue_Authenticating) GetCodeVerifier() []byte {
	if x != nil {
		return x.CodeVerifier
	}
	return nil
}

type CookieValue_Authenticated struct {
	state                  protoimpl.MessageState       `protogen:"open.v1"`
	AuthenticationMetadata *auth.AuthenticationMetadata `protobuf:"bytes,1,opt,name=authentication_metadata,json=authenticationMetadata,proto3" json:"authentication_metadata,omitempty"`
	Expiration             *timestamppb.Timestamp       `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	RefreshToken           string                       `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	DefaultExpiration      *durationpb.Duration         `protobuf:"bytes,4,opt,name=default_expiration,json=defaultExpiration,proto3" json:"default_expiration,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CookieValue_Authenticated) Reset() {
	*x = CookieValue_Authenticated{}
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CookieValue_Authenticated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookieValue_Authenticated) ProtoMessage() {}

func (x *CookieValue_Authenticated) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookieValue_Authenticated.ProtoReflect.Descriptor instead.
func (*CookieValue_Authenticated) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CookieValue_Authenticated) GetAuthenticationMetadata() *auth.AuthenticationMetadata {
	if x != nil {
		return x.AuthenticationMetadata
	}
	return nil
}

func (x *CookieValue_Authenticated) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *CookieValue_Authenticated) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *CookieValue_Authenticated) GetDefaultExpiration() *durationpb.Duration {
	if x != nil {
		return x.DefaultExpiration
	}
	return nil
}

var File_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_rawDesc = "" +
	"\n" +
	">github.com/buildbarn/bb-storage/pkg/proto/http/oidc/oidc.proto\x12\x13buildbarn.http.oidc\x1a9github.com/buildbarn/bb-storage/pkg/proto/auth/auth.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x05\n" +
	"\vCookieValue\x12Y\n" +
	"\x0eauthenticating\x18\x01 \x01(\v2/.buildbarn.http.oidc.CookieValue.AuthenticatingH\x00R\x0eauthenticating\x12V\n" +
	"\rauthenticated\x18\x02 \x01(\v2..buildbarn.http.oidc.CookieValue.AuthenticatedH\x00R\rauthenticated\x1a\x8e\x01\n" +
	"\x0eAuthenticating\x12%\n" +
	"\x0estate_verifier\x18\x01 \x01(\fR\rstateVerifier\x120\n" +
	"\x14original_request_uri\x18\x02 \x01(\tR\x12originalRequestUri\x12#\n" +
	"\rcode_verifier\x18\x03 \x01(\fR\fcodeVerifier\x1a\x9b\x02\n" +
	"\rAuthenticated\x12_\n" +
	"\x17authentication_metadata\x18\x01 \x01(\v2&.buildbarn.auth.AuthenticationMetadataR\x16authenticationMetadata\x12:\n" +
	"\n" +
	"expiration\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12H\n" +
	"\x12default_expiration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x11defaultExpirationB\x0f\n" +
	"\rsession_stateB5Z3github.com/buildbarn/bb-storage/pkg/proto/http/oidcb\x06proto3"

var (
	file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_rawDesc), len(file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_rawDescData
}

var file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_goTypes = []any{
	(*CookieValue)(nil),                 // 0: buildbarn.http.oidc.CookieValue
	(*CookieValue_Authenticating)(nil),  // 1: buildbarn.http.oidc.CookieValue.Authenticating
	(*CookieValue_Authenticated)(nil),   // 2: buildbarn.http.oidc.CookieValue.Authenticated
	(*auth.AuthenticationMetadata)(nil), // 3: buildbarn.auth.AuthenticationMetadata
	(*timestamppb.Timestamp)(nil),       // 4: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),         // 5: google.protobuf.Duration
}
var file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_depIdxs = []int32{
	1, // 0: buildbarn.http.oidc.CookieValue.authenticating:type_name -> buildbarn.http.oidc.CookieValue.Authenticating
	2, // 1: buildbarn.http.oidc.CookieValue.authenticated:type_name -> buildbarn.http.oidc.CookieValue.Authenticated
	3, // 2: buildbarn.http.oidc.CookieValue.Authenticated.authentication_metadata:type_name -> buildbarn.auth.AuthenticationMetadata
	4, // 3: buildbarn.http.oidc.CookieValue.Authenticated.expiration:type_name -> google.protobuf.Timestamp
	5, // 4: buildbarn.http.oidc.CookieValue.Authenticated.default_expiration:type_name -> google.protobuf.Duration
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_init() }
func file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_init() {
	if File_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto != nil {
		return
	}
	file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_msgTypes[0].OneofWrappers = []any{
		(*CookieValue_Authenticating_)(nil),
		(*CookieValue_Authenticated_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_rawDesc), len(file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto = out.File
	file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_goTypes = nil
	file_github_com_buildbarn_bb_storage_pkg_proto_http_oidc_oidc_proto_depIdxs = nil
}
