// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: github.com/buildbarn/bb-storage/pkg/proto/configuration/bb_copy/bb_copy.proto

package bb_copy

import (
	v2 "github.com/bazelbuild/remote-apis/build/bazel/remote/execution/v2"
	blobstore "github.com/buildbarn/bb-storage/pkg/proto/configuration/blobstore"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state                   protoimpl.MessageState                 `protogen:"open.v1"`
	Source                  *blobstore.BlobAccessConfiguration     `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Sink                    *blobstore.BlobAccessConfiguration     `protobuf:"bytes,2,opt,name=sink,proto3" json:"sink,omitempty"`
	Replicator              *blobstore.BlobReplicatorConfiguration `protobuf:"bytes,3,opt,name=replicator,proto3" json:"replicator,omitempty"`
	InstanceName            string                                 `protobuf:"bytes,4,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	Actions                 []*v2.Digest                           `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	Blobs                   []*v2.Digest                           `protobuf:"bytes,6,rep,name=blobs,proto3" json:"blobs,omitempty"`
	Directories             []*v2.Digest                           `protobuf:"bytes,7,rep,name=directories,proto3" json:"directories,omitempty"`
	Trees                   []*v2.Digest                           `protobuf:"bytes,8,rep,name=trees,proto3" json:"trees,omitempty"`
	MaximumMessageSizeBytes int64                                  `protobuf:"varint,9,opt,name=maximum_message_size_bytes,json=maximumMessageSizeBytes,proto3" json:"maximum_message_size_bytes,omitempty"`
	TraversalConcurrency    int32                                  `protobuf:"varint,10,opt,name=traversal_concurrency,json=traversalConcurrency,proto3" json:"traversal_concurrency,omitempty"`
	DigestFunction          v2.DigestFunction_Value                `protobuf:"varint,11,opt,name=digest_function,json=digestFunction,proto3,enum=build.bazel.remote.execution.v2.DigestFunction_Value" json:"digest_function,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetSource() *blobstore.BlobAccessConfiguration {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ApplicationConfiguration) GetSink() *blobstore.BlobAccessConfiguration {
	if x != nil {
		return x.Sink
	}
	return nil
}

func (x *ApplicationConfiguration) GetReplicator() *blobstore.BlobReplicatorConfiguration {
	if x != nil {
		return x.Replicator
	}
	return nil
}

func (x *ApplicationConfiguration) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *ApplicationConfiguration) GetActions() []*v2.Digest {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ApplicationConfiguration) GetBlobs() []*v2.Digest {
	if x != nil {
		return x.Blobs
	}
	return nil
}

func (x *ApplicationConfiguration) GetDirectories() []*v2.Digest {
	if x != nil {
		return x.Directories
	}
	return nil
}

func (x *ApplicationConfiguration) GetTrees() []*v2.Digest {
	if x != nil {
		return x.Trees
	}
	return nil
}

func (x *ApplicationConfiguration) GetMaximumMessageSizeBytes() int64 {
	if x != nil {
		return x.MaximumMessageSizeBytes
	}
	return 0
}

func (x *ApplicationConfiguration) GetTraversalConcurrency() int32 {
	if x != nil {
		return x.TraversalConcurrency
	}
	return 0
}

func (x *ApplicationConfiguration) GetDigestFunction() v2.DigestFunction_Value {
	if x != nil {
		return x.DigestFunction
	}
	return v2.DigestFunction_Value(0)
}

var File_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_rawDesc = "" +
	"\n" +
	"Mgithub.com/buildbarn/bb-storage/pkg/proto/configuration/bb_copy/bb_copy.proto\x12\x1fbuildbarn.configuration.bb_copy\x1a6build/bazel/remote/execution/v2/remote_execution.proto\x1aQgithub.com/buildbarn/bb-storage/pkg/proto/configuration/blobstore/blobstore.proto\"\xa1\x06\n" +
	"\x18ApplicationConfiguration\x12R\n" +
	"\x06source\x18\x01 \x01(\v2:.buildbarn.configuration.blobstore.BlobAccessConfigurationR\x06source\x12N\n" +
	"\x04sink\x18\x02 \x01(\v2:.buildbarn.configuration.blobstore.BlobAccessConfigurationR\x04sink\x12^\n" +
	"\n" +
	"replicator\x18\x03 \x01(\v2>.buildbarn.configuration.blobstore.BlobReplicatorConfigurationR\n" +
	"replicator\x12#\n" +
	"\rinstance_name\x18\x04 \x01(\tR\finstanceName\x12A\n" +
	"\aactions\x18\x05 \x03(\v2'.build.bazel.remote.execution.v2.DigestR\aactions\x12=\n" +
	"\x05blobs\x18\x06 \x03(\v2'.build.bazel.remote.execution.v2.DigestR\x05blobs\x12I\n" +
	"\vdirectories\x18\a \x03(\v2'.build.bazel.remote.execution.v2.DigestR\vdirectories\x12=\n" +
	"\x05trees\x18\b \x03(\v2'.build.bazel.remote.execution.v2.DigestR\x05trees\x12;\n" +
	"\x1amaximum_message_size_bytes\x18\t \x01(\x03R\x17maximumMessageSizeBytes\x123\n" +
	"\x15traversal_concurrency\x18\n" +
	" \x01(\x05R\x14traversalConcurrency\x12^\n" +
	"\x0fdigest_function\x18\v \x01(\x0e25.build.bazel.remote.execution.v2.DigestFunction.ValueR\x0edigestFunctionb\x06proto3"

var (
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_rawDesc), len(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_rawDescData
}

var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil),              // 0: buildbarn.configuration.bb_copy.ApplicationConfiguration
	(*blobstore.BlobAccessConfiguration)(nil),     // 1: buildbarn.configuration.blobstore.BlobAccessConfiguration
	(*blobstore.BlobReplicatorConfiguration)(nil), // 2: buildbarn.configuration.blobstore.BlobReplicatorConfiguration
	(*v2.Digest)(nil),                             // 3: build.bazel.remote.execution.v2.Digest
	(v2.DigestFunction_Value)(0),                  // 4: build.bazel.remote.execution.v2.DigestFunction.Value
}
var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_depIdxs = []int32{
	1, // 0: buildbarn.configuration.bb_copy.ApplicationConfiguration.source:type_name -> buildbarn.configuration.blobstore.BlobAccessConfiguration
	1, // 1: buildbarn.configuration.bb_copy.ApplicationConfiguration.sink:type_name -> buildbarn.configuration.blobstore.BlobAccessConfiguration
	2, // 2: buildbarn.configuration.bb_copy.ApplicationConfiguration.replicator:type_name -> buildbarn.configuration.blobstore.BlobReplicatorConfiguration
	3, // 3: buildbarn.configuration.bb_copy.ApplicationConfiguration.actions:type_name -> build.bazel.remote.execution.v2.Digest
	3, // 4: buildbarn.configuration.bb_copy.ApplicationConfiguration.blobs:type_name -> build.bazel.remote.execution.v2.Digest
	3, // 5: buildbarn.configuration.bb_copy.ApplicationConfiguration.directories:type_name -> build.bazel.remote.execution.v2.Digest
	3, // 6: buildbarn.configuration.bb_copy.ApplicationConfiguration.trees:type_name -> build.bazel.remote.execution.v2.Digest
	4, // 7: buildbarn.configuration.bb_copy.ApplicationConfiguration.digest_function:type_name -> build.bazel.remote.execution.v2.DigestFunction.Value
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_init()
}
func file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_init() {
	if File_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_rawDesc), len(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto = out.File
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_goTypes = nil
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_bb_copy_bb_copy_proto_depIdxs = nil
}
