load("@rules_go//go:def.bzl", "go_library", "go_test")

# Exported for mock generation purposes.

go_library(
    name = "cas",
    srcs = [
        "chunk_bytes_reader.go",
        "find_missing.go",
        "get_bytes.go",
        "get_read_closer_at.go",
        "into_writer.go",
        "is_single_chunk.go",
        "message_reader.go",
        "nested_blob_replicator.go",
        "put_reader.go",
        "read_blob_at.go",
        "replicator.go",
        "stream_reader.go",
    ],
    importpath = "github.com/buildbarn/bb-storage/pkg/cas",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/blobstore",
        "//pkg/blobstore/cdc",
        "//pkg/blobstore/chunk",
        "//pkg/capabilities",
        "//pkg/cas/reader",
        "//pkg/digest",
        "//pkg/util",
        "//pkg/zstd",
        "@bazel_remote_apis//build/bazel/remote/execution/v2:remote_execution_go_proto",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//encoding/protowire",
        "@org_golang_google_protobuf//proto",
    ],
)

go_test(
    name = "cas_test",
    srcs = [
        "nested_blob_replicator_test.go",
        "put_reader_test.go",
    ],
    deps = [
        ":cas",
        "//internal/mock",
        "//pkg/blobstore/chunk",
        "//pkg/digest",
        "//pkg/testutil",
        "//pkg/zstd",
        "@bazel_remote_apis//build/bazel/remote/execution/v2:remote_execution_go_proto",
        "@com_github_stretchr_testify//require",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//proto",
        "@org_uber_go_mock//gomock",
    ],
)
