load("@rules_go//go:def.bzl", "go_library", "go_test")

# Exported for mock generation purposes.
exports_files(["message_reader.go"])

go_library(
    name = "cas",
    srcs = [
        "blob_access_message_reader.go",
        "blob_access_replicator.go",
        "blob_access_stream_reader.go",
        "message_reader.go",
        "nested_blob_replicator.go",
        "replicator.go",
        "stream_reader.go",
    ],
    importpath = "github.com/buildbarn/bb-storage/pkg/cas",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/blobstore",
        "//pkg/blobstore/buffer",
        "//pkg/blobstore/replication",
        "//pkg/digest",
        "//pkg/util",
        "@bazel_remote_apis//build/bazel/remote/execution/v2:remote_execution_go_proto",
        "@org_golang_google_protobuf//encoding/protowire",
        "@org_golang_google_protobuf//proto",
    ],
)

go_test(
    name = "cas_test",
    srcs = ["nested_blob_replicator_test.go"],
    deps = [
        ":cas",
        "//internal/mock",
        "//pkg/blobstore/buffer",
        "//pkg/digest",
        "@bazel_remote_apis//build/bazel/remote/execution/v2:remote_execution_go_proto",
        "@com_github_stretchr_testify//require",
        "@org_uber_go_mock//gomock",
    ],
)
