load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "chunklist",
    srcs = [
        "caching_fetcher.go",
        "chunk_concatenating_reader.go",
        "chunk_list.go",
    ],
    importpath = "github.com/buildbarn/bb-storage/pkg/blobstore/chunklist",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/cas/reader",
        "//pkg/digest",
        "//pkg/ttlcache",
        "//pkg/util",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)
