// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: github.com/buildbarn/bb-storage/pkg/proto/configuration/rerun_action/rerun_action.proto

package rerun_action

import (
	v2 "github.com/bazelbuild/remote-apis/build/bazel/remote/execution/v2"
	grpc "github.com/buildbarn/bb-storage/pkg/proto/configuration/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state                   protoimpl.MessageState    `protogen:"open.v1"`
	GrpcClient              *grpc.ClientConfiguration `protobuf:"bytes,1,opt,name=grpc_client,json=grpcClient,proto3" json:"grpc_client,omitempty"`
	InstanceName            string                    `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	DigestFunction          v2.DigestFunction_Value   `protobuf:"varint,3,opt,name=digest_function,json=digestFunction,proto3,enum=build.bazel.remote.execution.v2.DigestFunction_Value" json:"digest_function,omitempty"`
	ActionDigest            *v2.Digest                `protobuf:"bytes,4,opt,name=action_digest,json=actionDigest,proto3" json:"action_digest,omitempty"`
	MaximumMessageSizeBytes int64                     `protobuf:"varint,5,opt,name=maximum_message_size_bytes,json=maximumMessageSizeBytes,proto3" json:"maximum_message_size_bytes,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetGrpcClient() *grpc.ClientConfiguration {
	if x != nil {
		return x.GrpcClient
	}
	return nil
}

func (x *ApplicationConfiguration) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *ApplicationConfiguration) GetDigestFunction() v2.DigestFunction_Value {
	if x != nil {
		return x.DigestFunction
	}
	return v2.DigestFunction_Value(0)
}

func (x *ApplicationConfiguration) GetActionDigest() *v2.Digest {
	if x != nil {
		return x.ActionDigest
	}
	return nil
}

func (x *ApplicationConfiguration) GetMaximumMessageSizeBytes() int64 {
	if x != nil {
		return x.MaximumMessageSizeBytes
	}
	return 0
}

var File_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_rawDesc = "" +
	"\n" +
	"Wgithub.com/buildbarn/bb-storage/pkg/proto/configuration/rerun_action/rerun_action.proto\x12$buildbarn.configuration.rerun_action\x1a6build/bazel/remote/execution/v2/remote_execution.proto\x1aGgithub.com/buildbarn/bb-storage/pkg/proto/configuration/grpc/grpc.proto\"\xfe\x02\n" +
	"\x18ApplicationConfiguration\x12R\n" +
	"\vgrpc_client\x18\x01 \x01(\v21.buildbarn.configuration.grpc.ClientConfigurationR\n" +
	"grpcClient\x12#\n" +
	"\rinstance_name\x18\x02 \x01(\tR\finstanceName\x12^\n" +
	"\x0fdigest_function\x18\x03 \x01(\x0e25.build.bazel.remote.execution.v2.DigestFunction.ValueR\x0edigestFunction\x12L\n" +
	"\raction_digest\x18\x04 \x01(\v2'.build.bazel.remote.execution.v2.DigestR\factionDigest\x12;\n" +
	"\x1amaximum_message_size_bytes\x18\x05 \x01(\x03R\x17maximumMessageSizeBytesb\x06proto3"

var (
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_rawDesc), len(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_rawDescData
}

var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil), // 0: buildbarn.configuration.rerun_action.ApplicationConfiguration
	(*grpc.ClientConfiguration)(nil), // 1: buildbarn.configuration.grpc.ClientConfiguration
	(v2.DigestFunction_Value)(0),     // 2: build.bazel.remote.execution.v2.DigestFunction.Value
	(*v2.Digest)(nil),                // 3: build.bazel.remote.execution.v2.Digest
}
var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_depIdxs = []int32{
	1, // 0: buildbarn.configuration.rerun_action.ApplicationConfiguration.grpc_client:type_name -> buildbarn.configuration.grpc.ClientConfiguration
	2, // 1: buildbarn.configuration.rerun_action.ApplicationConfiguration.digest_function:type_name -> build.bazel.remote.execution.v2.DigestFunction.Value
	3, // 2: buildbarn.configuration.rerun_action.ApplicationConfiguration.action_digest:type_name -> build.bazel.remote.execution.v2.Digest
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_init()
}
func file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_init() {
	if File_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_rawDesc), len(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto = out.File
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_goTypes = nil
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_rerun_action_rerun_action_proto_depIdxs = nil
}
