// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/configuration/x509/x509.proto

package x509

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientCertificateVerifierConfiguration struct {
	state                                protoimpl.MessageState `protogen:"open.v1"`
	ClientCertificateAuthorities         string                 `protobuf:"bytes,1,opt,name=client_certificate_authorities,json=clientCertificateAuthorities,proto3" json:"client_certificate_authorities,omitempty"`
	ValidationJmespathExpression         string                 `protobuf:"bytes,2,opt,name=validation_jmespath_expression,json=validationJmespathExpression,proto3" json:"validation_jmespath_expression,omitempty"`
	MetadataExtractionJmespathExpression string                 `protobuf:"bytes,3,opt,name=metadata_extraction_jmespath_expression,json=metadataExtractionJmespathExpression,proto3" json:"metadata_extraction_jmespath_expression,omitempty"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *ClientCertificateVerifierConfiguration) Reset() {
	*x = ClientCertificateVerifierConfiguration{}
	mi := &file_pkg_proto_configuration_x509_x509_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCertificateVerifierConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCertificateVerifierConfiguration) ProtoMessage() {}

func (x *ClientCertificateVerifierConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_x509_x509_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCertificateVerifierConfiguration.ProtoReflect.Descriptor instead.
func (*ClientCertificateVerifierConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_x509_x509_proto_rawDescGZIP(), []int{0}
}

func (x *ClientCertificateVerifierConfiguration) GetClientCertificateAuthorities() string {
	if x != nil {
		return x.ClientCertificateAuthorities
	}
	return ""
}

func (x *ClientCertificateVerifierConfiguration) GetValidationJmespathExpression() string {
	if x != nil {
		return x.ValidationJmespathExpression
	}
	return ""
}

func (x *ClientCertificateVerifierConfiguration) GetMetadataExtractionJmespathExpression() string {
	if x != nil {
		return x.MetadataExtractionJmespathExpression
	}
	return ""
}

var File_pkg_proto_configuration_x509_x509_proto protoreflect.FileDescriptor

const file_pkg_proto_configuration_x509_x509_proto_rawDesc = "" +
	"\n" +
	"'pkg/proto/configuration/x509/x509.proto\x12\x1cbuildbarn.configuration.x509\"\x8b\x02\n" +
	"&ClientCertificateVerifierConfiguration\x12D\n" +
	"\x1eclient_certificate_authorities\x18\x01 \x01(\tR\x1cclientCertificateAuthorities\x12D\n" +
	"\x1evalidation_jmespath_expression\x18\x02 \x01(\tR\x1cvalidationJmespathExpression\x12U\n" +
	"'metadata_extraction_jmespath_expression\x18\x03 \x01(\tR$metadataExtractionJmespathExpressionB>Z<github.com/buildbarn/bb-storage/pkg/proto/configuration/x509b\x06proto3"

var (
	file_pkg_proto_configuration_x509_x509_proto_rawDescOnce sync.Once
	file_pkg_proto_configuration_x509_x509_proto_rawDescData []byte
)

func file_pkg_proto_configuration_x509_x509_proto_rawDescGZIP() []byte {
	file_pkg_proto_configuration_x509_x509_proto_rawDescOnce.Do(func() {
		file_pkg_proto_configuration_x509_x509_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_x509_x509_proto_rawDesc), len(file_pkg_proto_configuration_x509_x509_proto_rawDesc)))
	})
	return file_pkg_proto_configuration_x509_x509_proto_rawDescData
}

var file_pkg_proto_configuration_x509_x509_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_configuration_x509_x509_proto_goTypes = []any{
	(*ClientCertificateVerifierConfiguration)(nil), // 0: buildbarn.configuration.x509.ClientCertificateVerifierConfiguration
}
var file_pkg_proto_configuration_x509_x509_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_configuration_x509_x509_proto_init() }
func file_pkg_proto_configuration_x509_x509_proto_init() {
	if File_pkg_proto_configuration_x509_x509_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_x509_x509_proto_rawDesc), len(file_pkg_proto_configuration_x509_x509_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_configuration_x509_x509_proto_goTypes,
		DependencyIndexes: file_pkg_proto_configuration_x509_x509_proto_depIdxs,
		MessageInfos:      file_pkg_proto_configuration_x509_x509_proto_msgTypes,
	}.Build()
	File_pkg_proto_configuration_x509_x509_proto = out.File
	file_pkg_proto_configuration_x509_x509_proto_goTypes = nil
	file_pkg_proto_configuration_x509_x509_proto_depIdxs = nil
}
