// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: github.com/buildbarn/bb-storage/pkg/proto/configuration/lossymap/lossymap.proto

package lossymap

import (
	blockdevice "github.com/buildbarn/bb-storage/pkg/proto/configuration/blockdevice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashMapConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Backend:
	//
	//	*HashMapConfiguration_InMemory_
	//	*HashMapConfiguration_OnBlockDevice
	Backend            isHashMapConfiguration_Backend `protobuf_oneof:"backend"`
	MaximumGetAttempts uint32                         `protobuf:"varint,3,opt,name=maximum_get_attempts,json=maximumGetAttempts,proto3" json:"maximum_get_attempts,omitempty"`
	MaximumPutAttempts int64                          `protobuf:"varint,4,opt,name=maximum_put_attempts,json=maximumPutAttempts,proto3" json:"maximum_put_attempts,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HashMapConfiguration) Reset() {
	*x = HashMapConfiguration{}
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashMapConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashMapConfiguration) ProtoMessage() {}

func (x *HashMapConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashMapConfiguration.ProtoReflect.Descriptor instead.
func (*HashMapConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_rawDescGZIP(), []int{0}
}

func (x *HashMapConfiguration) GetBackend() isHashMapConfiguration_Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *HashMapConfiguration) GetInMemory() *HashMapConfiguration_InMemory {
	if x != nil {
		if x, ok := x.Backend.(*HashMapConfiguration_InMemory_); ok {
			return x.InMemory
		}
	}
	return nil
}

func (x *HashMapConfiguration) GetOnBlockDevice() *blockdevice.Configuration {
	if x != nil {
		if x, ok := x.Backend.(*HashMapConfiguration_OnBlockDevice); ok {
			return x.OnBlockDevice
		}
	}
	return nil
}

func (x *HashMapConfiguration) GetMaximumGetAttempts() uint32 {
	if x != nil {
		return x.MaximumGetAttempts
	}
	return 0
}

func (x *HashMapConfiguration) GetMaximumPutAttempts() int64 {
	if x != nil {
		return x.MaximumPutAttempts
	}
	return 0
}

type isHashMapConfiguration_Backend interface {
	isHashMapConfiguration_Backend()
}

type HashMapConfiguration_InMemory_ struct {
	InMemory *HashMapConfiguration_InMemory `protobuf:"bytes,1,opt,name=in_memory,json=inMemory,proto3,oneof"`
}

type HashMapConfiguration_OnBlockDevice struct {
	OnBlockDevice *blockdevice.Configuration `protobuf:"bytes,2,opt,name=on_block_device,json=onBlockDevice,proto3,oneof"`
}

func (*HashMapConfiguration_InMemory_) isHashMapConfiguration_Backend() {}

func (*HashMapConfiguration_OnBlockDevice) isHashMapConfiguration_Backend() {}

type HashMapConfiguration_InMemory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       uint64                 `protobuf:"varint,1,opt,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashMapConfiguration_InMemory) Reset() {
	*x = HashMapConfiguration_InMemory{}
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashMapConfiguration_InMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashMapConfiguration_InMemory) ProtoMessage() {}

func (x *HashMapConfiguration_InMemory) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashMapConfiguration_InMemory.ProtoReflect.Descriptor instead.
func (*HashMapConfiguration_InMemory) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_rawDescGZIP(), []int{0, 0}
}

func (x *HashMapConfiguration_InMemory) GetEntries() uint64 {
	if x != nil {
		return x.Entries
	}
	return 0
}

var File_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_rawDesc = "" +
	"\n" +
	"Ogithub.com/buildbarn/bb-storage/pkg/proto/configuration/lossymap/lossymap.proto\x12 buildbarn.configuration.lossymap\x1aUgithub.com/buildbarn/bb-storage/pkg/proto/configuration/blockdevice/blockdevice.proto\"\xe9\x02\n" +
	"\x14HashMapConfiguration\x12^\n" +
	"\tin_memory\x18\x01 \x01(\v2?.buildbarn.configuration.lossymap.HashMapConfiguration.InMemoryH\x00R\binMemory\x12\\\n" +
	"\x0fon_block_device\x18\x02 \x01(\v22.buildbarn.configuration.blockdevice.ConfigurationH\x00R\ronBlockDevice\x120\n" +
	"\x14maximum_get_attempts\x18\x03 \x01(\rR\x12maximumGetAttempts\x120\n" +
	"\x14maximum_put_attempts\x18\x04 \x01(\x03R\x12maximumPutAttempts\x1a$\n" +
	"\bInMemory\x12\x18\n" +
	"\aentries\x18\x01 \x01(\x04R\aentriesB\t\n" +
	"\abackendBBZ@github.com/buildbarn/bb-storage/pkg/proto/configuration/lossymapb\x06proto3"

var (
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_rawDesc), len(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_rawDescData
}

var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_goTypes = []any{
	(*HashMapConfiguration)(nil),          // 0: buildbarn.configuration.lossymap.HashMapConfiguration
	(*HashMapConfiguration_InMemory)(nil), // 1: buildbarn.configuration.lossymap.HashMapConfiguration.InMemory
	(*blockdevice.Configuration)(nil),     // 2: buildbarn.configuration.blockdevice.Configuration
}
var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_depIdxs = []int32{
	1, // 0: buildbarn.configuration.lossymap.HashMapConfiguration.in_memory:type_name -> buildbarn.configuration.lossymap.HashMapConfiguration.InMemory
	2, // 1: buildbarn.configuration.lossymap.HashMapConfiguration.on_block_device:type_name -> buildbarn.configuration.blockdevice.Configuration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_init()
}
func file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_init() {
	if File_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto != nil {
		return
	}
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_msgTypes[0].OneofWrappers = []any{
		(*HashMapConfiguration_InMemory_)(nil),
		(*HashMapConfiguration_OnBlockDevice)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_rawDesc), len(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto = out.File
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_goTypes = nil
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_lossymap_lossymap_proto_depIdxs = nil
}
