load("@rules_go//go:def.bzl", "go_library")

# Exported for mock generation purposes.
exports_files(["message_reader.go"])

go_library(
    name = "storage",
    srcs = ["message_reader.go"],
    importpath = "github.com/buildbarn/bb-storage/pkg/storage",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/digest",
        "@org_golang_google_protobuf//proto",
    ],
)
