// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: github.com/buildbarn/bb-storage/pkg/proto/configuration/eviction/eviction.proto

package eviction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheReplacementPolicy int32

const (
	CacheReplacementPolicy_UNKNOWN             CacheReplacementPolicy = 0
	CacheReplacementPolicy_FIRST_IN_FIRST_OUT  CacheReplacementPolicy = 1
	CacheReplacementPolicy_LEAST_RECENTLY_USED CacheReplacementPolicy = 2
	CacheReplacementPolicy_RANDOM_REPLACEMENT  CacheReplacementPolicy = 3
)

// Enum value maps for CacheReplacementPolicy.
var (
	CacheReplacementPolicy_name = map[int32]string{
		0: "UNKNOWN",
		1: "FIRST_IN_FIRST_OUT",
		2: "LEAST_RECENTLY_USED",
		3: "RANDOM_REPLACEMENT",
	}
	CacheReplacementPolicy_value = map[string]int32{
		"UNKNOWN":             0,
		"FIRST_IN_FIRST_OUT":  1,
		"LEAST_RECENTLY_USED": 2,
		"RANDOM_REPLACEMENT":  3,
	}
)

func (x CacheReplacementPolicy) Enum() *CacheReplacementPolicy {
	p := new(CacheReplacementPolicy)
	*p = x
	return p
}

func (x CacheReplacementPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CacheReplacementPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_enumTypes[0].Descriptor()
}

func (CacheReplacementPolicy) Type() protoreflect.EnumType {
	return &file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_enumTypes[0]
}

func (x CacheReplacementPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CacheReplacementPolicy.Descriptor instead.
func (CacheReplacementPolicy) EnumDescriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_rawDescGZIP(), []int{0}
}

var File_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_rawDesc = "" +
	"\n" +
	"Ogithub.com/buildbarn/bb-storage/pkg/proto/configuration/eviction/eviction.proto\x12 buildbarn.configuration.eviction*n\n" +
	"\x16CacheReplacementPolicy\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x16\n" +
	"\x12FIRST_IN_FIRST_OUT\x10\x01\x12\x17\n" +
	"\x13LEAST_RECENTLY_USED\x10\x02\x12\x16\n" +
	"\x12RANDOM_REPLACEMENT\x10\x03BBZ@github.com/buildbarn/bb-storage/pkg/proto/configuration/evictionb\x06proto3"

var (
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_rawDesc), len(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_rawDescData
}

var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_goTypes = []any{
	(CacheReplacementPolicy)(0), // 0: buildbarn.configuration.eviction.CacheReplacementPolicy
}
var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_init()
}
func file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_init() {
	if File_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_rawDesc), len(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_depIdxs,
		EnumInfos:         file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_enumTypes,
	}.Build()
	File_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto = out.File
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_goTypes = nil
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_eviction_eviction_proto_depIdxs = nil
}
