// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.28.1
// source: pkg/proto/configuration/eviction/eviction.proto

package eviction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheReplacementPolicy int32

const (
	CacheReplacementPolicy_UNKNOWN             CacheReplacementPolicy = 0
	CacheReplacementPolicy_FIRST_IN_FIRST_OUT  CacheReplacementPolicy = 1
	CacheReplacementPolicy_LEAST_RECENTLY_USED CacheReplacementPolicy = 2
	CacheReplacementPolicy_RANDOM_REPLACEMENT  CacheReplacementPolicy = 3
)

// Enum value maps for CacheReplacementPolicy.
var (
	CacheReplacementPolicy_name = map[int32]string{
		0: "UNKNOWN",
		1: "FIRST_IN_FIRST_OUT",
		2: "LEAST_RECENTLY_USED",
		3: "RANDOM_REPLACEMENT",
	}
	CacheReplacementPolicy_value = map[string]int32{
		"UNKNOWN":             0,
		"FIRST_IN_FIRST_OUT":  1,
		"LEAST_RECENTLY_USED": 2,
		"RANDOM_REPLACEMENT":  3,
	}
)

func (x CacheReplacementPolicy) Enum() *CacheReplacementPolicy {
	p := new(CacheReplacementPolicy)
	*p = x
	return p
}

func (x CacheReplacementPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CacheReplacementPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_configuration_eviction_eviction_proto_enumTypes[0].Descriptor()
}

func (CacheReplacementPolicy) Type() protoreflect.EnumType {
	return &file_pkg_proto_configuration_eviction_eviction_proto_enumTypes[0]
}

func (x CacheReplacementPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CacheReplacementPolicy.Descriptor instead.
func (CacheReplacementPolicy) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_eviction_eviction_proto_rawDescGZIP(), []int{0}
}

var File_pkg_proto_configuration_eviction_eviction_proto protoreflect.FileDescriptor

var file_pkg_proto_configuration_eviction_eviction_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x65, 0x76, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x65, 0x76, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x20, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x62, 0x61, 0x72, 0x6e, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x65, 0x76, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2a, 0x6e, 0x0a, 0x16, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x46, 0x49,
	0x52, 0x53, 0x54, 0x5f, 0x49, 0x4e, 0x5f, 0x46, 0x49, 0x52, 0x53, 0x54, 0x5f, 0x4f, 0x55, 0x54,
	0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x4c, 0x45, 0x41, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x43, 0x45,
	0x4e, 0x54, 0x4c, 0x59, 0x5f, 0x55, 0x53, 0x45, 0x44, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x52,
	0x41, 0x4e, 0x44, 0x4f, 0x4d, 0x5f, 0x52, 0x45, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x4d, 0x45, 0x4e,
	0x54, 0x10, 0x03, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x62, 0x61, 0x72, 0x6e, 0x2f, 0x62, 0x62, 0x2d, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x65,
	0x76, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_configuration_eviction_eviction_proto_rawDescOnce sync.Once
	file_pkg_proto_configuration_eviction_eviction_proto_rawDescData = file_pkg_proto_configuration_eviction_eviction_proto_rawDesc
)

func file_pkg_proto_configuration_eviction_eviction_proto_rawDescGZIP() []byte {
	file_pkg_proto_configuration_eviction_eviction_proto_rawDescOnce.Do(func() {
		file_pkg_proto_configuration_eviction_eviction_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_configuration_eviction_eviction_proto_rawDescData)
	})
	return file_pkg_proto_configuration_eviction_eviction_proto_rawDescData
}

var file_pkg_proto_configuration_eviction_eviction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_configuration_eviction_eviction_proto_goTypes = []interface{}{
	(CacheReplacementPolicy)(0), // 0: buildbarn.configuration.eviction.CacheReplacementPolicy
}
var file_pkg_proto_configuration_eviction_eviction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_configuration_eviction_eviction_proto_init() }
func file_pkg_proto_configuration_eviction_eviction_proto_init() {
	if File_pkg_proto_configuration_eviction_eviction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_configuration_eviction_eviction_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_configuration_eviction_eviction_proto_goTypes,
		DependencyIndexes: file_pkg_proto_configuration_eviction_eviction_proto_depIdxs,
		EnumInfos:         file_pkg_proto_configuration_eviction_eviction_proto_enumTypes,
	}.Build()
	File_pkg_proto_configuration_eviction_eviction_proto = out.File
	file_pkg_proto_configuration_eviction_eviction_proto_rawDesc = nil
	file_pkg_proto_configuration_eviction_eviction_proto_goTypes = nil
	file_pkg_proto_configuration_eviction_eviction_proto_depIdxs = nil
}
