load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "referenceexpanding",
    srcs = ["reference_expanding_blob_access.go"],
    importpath = "github.com/buildbarn/bb-storage/pkg/blobstore/referenceexpanding",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/blobstore",
        "//pkg/blobstore/buffer",
        "//pkg/blobstore/slicing",
        "//pkg/cas",
        "//pkg/cloud/aws",
        "//pkg/cloud/gcp",
        "//pkg/digest",
        "//pkg/proto/icas",
        "//pkg/util",
        "//pkg/zstd",
        "@bazel_remote_apis//build/bazel/remote/execution/v2:remote_execution_go_proto",
        "@com_github_aws_aws_sdk_go_v2//aws",
        "@com_github_aws_aws_sdk_go_v2_service_s3//:s3",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)

go_test(
    name = "referenceexpanding_test",
    srcs = ["reference_expanding_blob_access_test.go"],
    deps = [
        ":referenceexpanding",
        "//internal/mock",
        "//pkg/blobstore/buffer",
        "//pkg/blobstore/cdc",
        "//pkg/digest",
        "//pkg/proto/icas",
        "//pkg/testutil",
        "//pkg/zstd",
        "@bazel_remote_apis//build/bazel/remote/execution/v2:remote_execution_go_proto",
        "@com_github_aws_aws_sdk_go_v2//aws",
        "@com_github_aws_aws_sdk_go_v2_service_s3//:s3",
        "@com_github_aws_aws_sdk_go_v2_service_s3//types",
        "@com_github_klauspost_compress//zstd",
        "@com_github_stretchr_testify//require",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_uber_go_mock//gomock",
    ],
)
