// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: pkg/proto/configuration/tls/tls.proto

package tls

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerCertificateAuthorities string       `protobuf:"bytes,1,opt,name=server_certificate_authorities,json=serverCertificateAuthorities,proto3" json:"server_certificate_authorities,omitempty"`
	CipherSuites                 []string     `protobuf:"bytes,4,rep,name=cipher_suites,json=cipherSuites,proto3" json:"cipher_suites,omitempty"`
	ServerName                   string       `protobuf:"bytes,5,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ClientKeyPair                *X509KeyPair `protobuf:"bytes,6,opt,name=client_key_pair,json=clientKeyPair,proto3" json:"client_key_pair,omitempty"`
}

func (x *ClientConfiguration) Reset() {
	*x = ClientConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_configuration_tls_tls_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfiguration) ProtoMessage() {}

func (x *ClientConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_tls_tls_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfiguration.ProtoReflect.Descriptor instead.
func (*ClientConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_tls_tls_proto_rawDescGZIP(), []int{0}
}

func (x *ClientConfiguration) GetServerCertificateAuthorities() string {
	if x != nil {
		return x.ServerCertificateAuthorities
	}
	return ""
}

func (x *ClientConfiguration) GetCipherSuites() []string {
	if x != nil {
		return x.CipherSuites
	}
	return nil
}

func (x *ClientConfiguration) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ClientConfiguration) GetClientKeyPair() *X509KeyPair {
	if x != nil {
		return x.ClientKeyPair
	}
	return nil
}

type ServerConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CipherSuites  []string     `protobuf:"bytes,3,rep,name=cipher_suites,json=cipherSuites,proto3" json:"cipher_suites,omitempty"`
	ServerKeyPair *X509KeyPair `protobuf:"bytes,4,opt,name=server_key_pair,json=serverKeyPair,proto3" json:"server_key_pair,omitempty"`
}

func (x *ServerConfiguration) Reset() {
	*x = ServerConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_configuration_tls_tls_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfiguration) ProtoMessage() {}

func (x *ServerConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_tls_tls_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfiguration.ProtoReflect.Descriptor instead.
func (*ServerConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_tls_tls_proto_rawDescGZIP(), []int{1}
}

func (x *ServerConfiguration) GetCipherSuites() []string {
	if x != nil {
		return x.CipherSuites
	}
	return nil
}

func (x *ServerConfiguration) GetServerKeyPair() *X509KeyPair {
	if x != nil {
		return x.ServerKeyPair
	}
	return nil
}

type X509KeyPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to KeyPair:
	//
	//	*X509KeyPair_Inline_
	//	*X509KeyPair_Files_
	KeyPair isX509KeyPair_KeyPair `protobuf_oneof:"key_pair"`
}

func (x *X509KeyPair) Reset() {
	*x = X509KeyPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_configuration_tls_tls_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *X509KeyPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X509KeyPair) ProtoMessage() {}

func (x *X509KeyPair) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_tls_tls_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X509KeyPair.ProtoReflect.Descriptor instead.
func (*X509KeyPair) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_tls_tls_proto_rawDescGZIP(), []int{2}
}

func (m *X509KeyPair) GetKeyPair() isX509KeyPair_KeyPair {
	if m != nil {
		return m.KeyPair
	}
	return nil
}

func (x *X509KeyPair) GetInline() *X509KeyPair_Inline {
	if x, ok := x.GetKeyPair().(*X509KeyPair_Inline_); ok {
		return x.Inline
	}
	return nil
}

func (x *X509KeyPair) GetFiles() *X509KeyPair_Files {
	if x, ok := x.GetKeyPair().(*X509KeyPair_Files_); ok {
		return x.Files
	}
	return nil
}

type isX509KeyPair_KeyPair interface {
	isX509KeyPair_KeyPair()
}

type X509KeyPair_Inline_ struct {
	Inline *X509KeyPair_Inline `protobuf:"bytes,1,opt,name=inline,proto3,oneof"`
}

type X509KeyPair_Files_ struct {
	Files *X509KeyPair_Files `protobuf:"bytes,2,opt,name=files,proto3,oneof"`
}

func (*X509KeyPair_Inline_) isX509KeyPair_KeyPair() {}

func (*X509KeyPair_Files_) isX509KeyPair_KeyPair() {}

type X509KeyPair_Inline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Certificate string `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	PrivateKey  string `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
}

func (x *X509KeyPair_Inline) Reset() {
	*x = X509KeyPair_Inline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_configuration_tls_tls_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *X509KeyPair_Inline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X509KeyPair_Inline) ProtoMessage() {}

func (x *X509KeyPair_Inline) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_tls_tls_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X509KeyPair_Inline.ProtoReflect.Descriptor instead.
func (*X509KeyPair_Inline) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_tls_tls_proto_rawDescGZIP(), []int{2, 0}
}

func (x *X509KeyPair_Inline) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *X509KeyPair_Inline) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type X509KeyPair_Files struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CertificatePath string               `protobuf:"bytes,1,opt,name=certificate_path,json=certificatePath,proto3" json:"certificate_path,omitempty"`
	PrivateKeyPath  string               `protobuf:"bytes,2,opt,name=private_key_path,json=privateKeyPath,proto3" json:"private_key_path,omitempty"`
	RefreshInterval *durationpb.Duration `protobuf:"bytes,4,opt,name=refresh_interval,json=refreshInterval,proto3" json:"refresh_interval,omitempty"`
}

func (x *X509KeyPair_Files) Reset() {
	*x = X509KeyPair_Files{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_configuration_tls_tls_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *X509KeyPair_Files) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X509KeyPair_Files) ProtoMessage() {}

func (x *X509KeyPair_Files) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_tls_tls_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X509KeyPair_Files.ProtoReflect.Descriptor instead.
func (*X509KeyPair_Files) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_tls_tls_proto_rawDescGZIP(), []int{2, 1}
}

func (x *X509KeyPair_Files) GetCertificatePath() string {
	if x != nil {
		return x.CertificatePath
	}
	return ""
}

func (x *X509KeyPair_Files) GetPrivateKeyPath() string {
	if x != nil {
		return x.PrivateKeyPath
	}
	return ""
}

func (x *X509KeyPair_Files) GetRefreshInterval() *durationpb.Duration {
	if x != nil {
		return x.RefreshInterval
	}
	return nil
}

var File_pkg_proto_configuration_tls_tls_proto protoreflect.FileDescriptor

var file_pkg_proto_configuration_tls_tls_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x74, 0x6c, 0x73, 0x2f, 0x74, 0x6c,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x62, 0x61,
	0x72, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x74, 0x6c, 0x73, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xff, 0x01, 0x0a, 0x13, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x44, 0x0a, 0x1e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x1c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x5f, 0x73, 0x75, 0x69,
	0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x53, 0x75, 0x69, 0x74, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x62, 0x61, 0x72, 0x6e, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x74, 0x6c, 0x73, 0x2e,
	0x58, 0x35, 0x30, 0x39, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0d, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03,
	0x4a, 0x04, 0x08, 0x03, 0x10, 0x04, 0x22, 0x98, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23,
	0x0a, 0x0d, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x5f, 0x73, 0x75, 0x69, 0x74, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x53, 0x75, 0x69,
	0x74, 0x65, 0x73, 0x12, 0x50, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6b, 0x65,
	0x79, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x62, 0x61, 0x72, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x74, 0x6c, 0x73, 0x2e, 0x58, 0x35, 0x30, 0x39, 0x4b,
	0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4b, 0x65,
	0x79, 0x50, 0x61, 0x69, 0x72, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x4a, 0x04, 0x08, 0x02, 0x10,
	0x03, 0x22, 0x9e, 0x03, 0x0a, 0x0b, 0x58, 0x35, 0x30, 0x39, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69,
	0x72, 0x12, 0x49, 0x0a, 0x06, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2f, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x62, 0x61, 0x72, 0x6e, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x74, 0x6c, 0x73, 0x2e,
	0x58, 0x35, 0x30, 0x39, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x2e, 0x49, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x48, 0x00, 0x52, 0x06, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x46, 0x0a, 0x05,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x62, 0x61, 0x72, 0x6e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x74, 0x6c, 0x73, 0x2e, 0x58, 0x35, 0x30, 0x39, 0x4b, 0x65,
	0x79, 0x50, 0x61, 0x69, 0x72, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52, 0x05, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x1a, 0x4b, 0x0a, 0x06, 0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x1a, 0xa2, 0x01, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x63,
	0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x44, 0x0a, 0x10, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x42, 0x0a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x61,
	0x69, 0x72, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x62, 0x61, 0x72, 0x6e, 0x2f, 0x62, 0x62, 0x2d, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x74, 0x6c,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_configuration_tls_tls_proto_rawDescOnce sync.Once
	file_pkg_proto_configuration_tls_tls_proto_rawDescData = file_pkg_proto_configuration_tls_tls_proto_rawDesc
)

func file_pkg_proto_configuration_tls_tls_proto_rawDescGZIP() []byte {
	file_pkg_proto_configuration_tls_tls_proto_rawDescOnce.Do(func() {
		file_pkg_proto_configuration_tls_tls_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_configuration_tls_tls_proto_rawDescData)
	})
	return file_pkg_proto_configuration_tls_tls_proto_rawDescData
}

var file_pkg_proto_configuration_tls_tls_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_configuration_tls_tls_proto_goTypes = []interface{}{
	(*ClientConfiguration)(nil), // 0: buildbarn.configuration.tls.ClientConfiguration
	(*ServerConfiguration)(nil), // 1: buildbarn.configuration.tls.ServerConfiguration
	(*X509KeyPair)(nil),         // 2: buildbarn.configuration.tls.X509KeyPair
	(*X509KeyPair_Inline)(nil),  // 3: buildbarn.configuration.tls.X509KeyPair.Inline
	(*X509KeyPair_Files)(nil),   // 4: buildbarn.configuration.tls.X509KeyPair.Files
	(*durationpb.Duration)(nil), // 5: google.protobuf.Duration
}
var file_pkg_proto_configuration_tls_tls_proto_depIdxs = []int32{
	2, // 0: buildbarn.configuration.tls.ClientConfiguration.client_key_pair:type_name -> buildbarn.configuration.tls.X509KeyPair
	2, // 1: buildbarn.configuration.tls.ServerConfiguration.server_key_pair:type_name -> buildbarn.configuration.tls.X509KeyPair
	3, // 2: buildbarn.configuration.tls.X509KeyPair.inline:type_name -> buildbarn.configuration.tls.X509KeyPair.Inline
	4, // 3: buildbarn.configuration.tls.X509KeyPair.files:type_name -> buildbarn.configuration.tls.X509KeyPair.Files
	5, // 4: buildbarn.configuration.tls.X509KeyPair.Files.refresh_interval:type_name -> google.protobuf.Duration
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_proto_configuration_tls_tls_proto_init() }
func file_pkg_proto_configuration_tls_tls_proto_init() {
	if File_pkg_proto_configuration_tls_tls_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_configuration_tls_tls_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_configuration_tls_tls_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_configuration_tls_tls_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*X509KeyPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_configuration_tls_tls_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*X509KeyPair_Inline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_configuration_tls_tls_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*X509KeyPair_Files); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_proto_configuration_tls_tls_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*X509KeyPair_Inline_)(nil),
		(*X509KeyPair_Files_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_configuration_tls_tls_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_configuration_tls_tls_proto_goTypes,
		DependencyIndexes: file_pkg_proto_configuration_tls_tls_proto_depIdxs,
		MessageInfos:      file_pkg_proto_configuration_tls_tls_proto_msgTypes,
	}.Build()
	File_pkg_proto_configuration_tls_tls_proto = out.File
	file_pkg_proto_configuration_tls_tls_proto_rawDesc = nil
	file_pkg_proto_configuration_tls_tls_proto_goTypes = nil
	file_pkg_proto_configuration_tls_tls_proto_depIdxs = nil
}
