// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: github.com/buildbarn/bb-storage/pkg/proto/configuration/cloud/gcp/gcp.proto

package gcp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientOptionsConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientOptionsConfiguration) Reset() {
	*x = ClientOptionsConfiguration{}
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientOptionsConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOptionsConfiguration) ProtoMessage() {}

func (x *ClientOptionsConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOptionsConfiguration.ProtoReflect.Descriptor instead.
func (*ClientOptionsConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_rawDescGZIP(), []int{0}
}

var File_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_rawDesc = "" +
	"\n" +
	"Kgithub.com/buildbarn/bb-storage/pkg/proto/configuration/cloud/gcp/gcp.proto\x12!buildbarn.configuration.cloud.gcp\"\x1c\n" +
	"\x1aClientOptionsConfigurationBCZAgithub.com/buildbarn/bb-storage/pkg/proto/configuration/cloud/gcpb\x06proto3"

var (
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_rawDesc), len(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_rawDescData
}

var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_goTypes = []any{
	(*ClientOptionsConfiguration)(nil), // 0: buildbarn.configuration.cloud.gcp.ClientOptionsConfiguration
}
var file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_init() }
func file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_init() {
	if File_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_rawDesc), len(file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto = out.File
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_goTypes = nil
	file_github_com_buildbarn_bb_storage_pkg_proto_configuration_cloud_gcp_gcp_proto_depIdxs = nil
}
